/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mapb.javautilities;

import org.junit.jupiter.api.Test;

import com.mapb.javautilities.utilities.ValidarDni;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void TestDNI1() {
    	boolean prueba = ValidarDni.validarDni("17483753G");
    	assertTrue(prueba);
    }
}
